# model params
model_type: 'EDM'
net_type: 'UNet'
diffusion:
  sigma_data: 0.5
  p_mean: -1.2
  p_std: 1.2
  sigma_min: 0.002
  sigma_max: 80
  rho: 7
network:
  image_shape: [3, 32, 32]
  n_channels: 128
  ch_mults: [1, 2, 2, 2]
  is_attn: [False, True, False, False]
  dropout: 0.1
  n_blocks: 2
  use_res_for_updown: False

# training params
n_epoch: 2000
batch_size: 128
lrate: 2.0e-4
load_epoch: -1
flip: True

# testing params
n_sample: 30
save_dir: './2000_unconditional_EDM'
save_model: True
