# model params
ddpm:
  n_T: 1000
  betas: [1.0e-4, 0.02]
unet:
  image_shape: [3, 32, 32]
  n_channels: 128
  ch_mults: [1, 2, 2, 2]
  is_attn: [False, True, False, False]
  dropout: 0.1
  n_blocks: 2
  use_res_for_updown: False

# training params
n_epoch: 2000
batch_size: 128
lrate: 2.0e-4
load_epoch: -1
flip: True

# testing params
n_sample: 30
save_dir: './2000_unconditional'
save_model: True
